// js/handstand-data.js
// Handstand-Press-Praxis: ein "Class"-Menü aus 5 Blöcken (A–E). Anders als PLAN
// ist dies keine lineare Phasen-Progression — pro Einheit wählt man EINEN Block.
// Jede Übung hat eine kurze deutsche Anleitung (howto), damit niemand googeln muss.
window.HANDSTAND = {
  blocks: [
    {
      id: 'a-warmup',
      letter: 'A',
      name: 'Warm-up',
      duration: '5–8 min',
      goal: 'Handgelenke, Schultern & Core aktivieren',
      exercises: [
        { id: 'a-cardio',             name: 'Leichtes Cardio',        prescription: '5 min',           howto: 'Locker einlaufen, Hampelmänner oder Seilspringen – Hauptsache der Kreislauf kommt in Gang und die Muskeln werden warm.' },
        { id: 'a-wrist-circles',      name: 'Wrist Circles',          prescription: '2×30 Sek',        howto: 'Hände vor dem Körper falten und die Handgelenke langsam in großen Kreisen bewegen, beide Richtungen.' },
        { id: 'a-scapula-pushups',    name: 'Scapula Push-Ups',       prescription: '2×10',            howto: 'Im hohen Plank die Arme gestreckt lassen und nur die Schulterblätter zusammen- und auseinanderschieben. Die Brust hebt und senkt sich minimal.' },
        { id: 'a-downward-dog',       name: 'Downward Facing Dog',    prescription: '30–45 Sek',       howto: 'Herabschauender Hund: Hüfte hoch, Rücken lang, Fersen Richtung Boden drücken. Schultern aktiv vom Boden wegschieben.' },
        { id: 'a-wrist-pushups',      name: 'Wrist Push-Ups (auf Knien)', prescription: '2×10',        howto: 'Auf den Knien, Handflächen am Boden, Finger zeigen nach vorne. Das Gewicht sanft nach vorne über die Handgelenke wiegen, um sie zu kräftigen.' },
        { id: 'a-arm-circles',        name: 'Arm Circles',            prescription: 'je 15–20',        howto: 'Arme seitlich ausstrecken und kontrolliert vor- und rückwärts kreisen, erst klein, dann größer.' },
        { id: 'a-cat-cow',            name: 'Cat-Cow Stretch',        prescription: '10–15 Wdh.',      howto: 'Im Vierfüßlerstand abwechselnd den Rücken rund machen (Katze) und ins Hohlkreuz sinken (Kuh), mit der Atmung fließen.' },
        { id: 'a-plank-shoulder-taps', name: 'Plank Shoulder Taps',   prescription: '2×20 Taps',       howto: 'Im Plank abwechselnd mit einer Hand die gegenüberliegende Schulter antippen. Hüfte ruhig halten, kein Schaukeln.' },
        { id: 'a-finger-pulses',      name: 'Finger Pulses',          prescription: '2×15',            howto: 'Handflächen am Boden, Finger leicht anheben und mit den Fingerspitzen aktiv in den Boden drücken – eine pumpende Bewegung für die Handgelenke.' },
        { id: 'a-scapula-pullups',    name: 'Scapula Pull-Ups',       prescription: '2×8',             howto: 'An der Stange (oder an Ringen) mit gestreckten Armen hängen und nur über die Schulterblätter den Körper minimal nach oben ziehen und wieder absenken.' },
        { id: 'a-hollow-hold',        name: 'Hollow Body Hold (leicht)', prescription: '20–30 Sek',    howto: 'Auf dem Rücken, unterer Rücken fest am Boden, Schultern und Beine leicht anheben. Für die leichtere Variante die Knie beugen.' },
        { id: 'a-hip-circles',        name: 'Hip Circles (CARs)',     prescription: '5–8 pro Richtung', howto: 'Im Stand oder Vierfüßler ein Knie groß und kontrolliert im Kreis führen – volle Bewegungsreichweite der Hüfte.' },
      ],
    },
    {
      id: 'b-mobility',
      letter: 'B',
      name: 'Mobility',
      duration: '8–10 min',
      goal: 'Hüfte + Hamstrings für Press öffnen',
      exercises: [
        { id: 'b-sumo-squat-hold',    name: 'Sumo Squat Hold',        prescription: '2×30 Sek',        howto: 'Breiter Stand, Füße nach außen, tief in die Hocke sinken und mit den Ellbogen die Knie sanft nach außen drücken. Brust aufrecht.' },
        { id: 'b-cossack-squats',     name: 'Cossack Squats',         prescription: '8–10 pro Seite',  howto: 'Breiter Stand, das Gewicht auf ein gebeugtes Bein verlagern, das andere Bein gestreckt. Seitlich tief absinken, dann zur anderen Seite.' },
        { id: 'b-frog-stretch',       name: 'Frog Stretch',           prescription: '2×30 Sek',        howto: 'Knie weit auseinander am Boden, Unterschenkel nach außen, die Hüfte langsam Richtung Fersen schieben. Dehnt die Adduktoren.' },
        { id: 'b-forward-fold-flat',  name: 'Forward Fold (Flat Back)', prescription: '2×20 Sek',      howto: 'Aus dem Stand mit geradem Rücken nach vorne beugen, bis der Oberkörper waagerecht ist. Hamstrings lang, Rücken flach.' },
        { id: 'b-straddle-fold',      name: 'Straddle Forward Fold',  prescription: '2×20 Sek',        howto: 'Im weiten Grätschsitz oder -stand mit langem Rücken nach vorne falten – aktiv, nicht in den Rücken runden.' },
        { id: 'b-pancake',            name: 'Pancake Stretch',        prescription: '30–45 Sek',       howto: 'Im Grätschsitz den Oberkörper mit geradem Rücken nach vorne und unten Richtung Boden bringen. Beine gestreckt, Zehen hoch.' },
        { id: 'b-jefferson-curl',     name: 'Jefferson Curl (leicht)', prescription: '5–8 Wdh.',       howto: 'Auf einer erhöhten Fläche stehend Wirbel für Wirbel langsam nach unten rollen und wieder auf. Nur leichtes Gewicht, kontrolliert.' },
        { id: 'b-lunge-hipflexor',    name: 'Lunge Hip Flexor Stretch', prescription: '2×30 Sek/Seite', howto: 'Tiefer Ausfallschritt, hinteres Knie am Boden, das Becken nach vorne schieben, bis es vorne in der Hüfte zieht.' },
        { id: 'b-shoulder-wall',      name: 'Shoulder Wall Stretch',  prescription: '2×20–30 Sek',     howto: 'Unterarme oder Hände an der Wand (oder erhöht), die Brust Richtung Boden sinken lassen. Öffnet die Schultern für den Überkopf-Stütz.' },
        { id: 'b-active-hamstring-kicks', name: 'Active Hamstring Kicks', prescription: '10–15/Bein',  howto: 'Im Stand das gestreckte Bein kontrolliert nach vorne/oben schwingen, die gegengleiche Hand zur Fußspitze. Aktiv, nicht reißen.' },
        { id: 'b-pancake-pulses',     name: 'Pancake Pulses (aktiv)', prescription: '15–20',           howto: 'In der Pancake-Position kleine, aktive Auf-und-ab-Bewegungen Richtung Boden – die Muskeln arbeiten lassen.' },
        { id: 'b-elevated-pike-stretch', name: 'Elevated Pike Stretch', prescription: '30 Sek',        howto: 'Füße erhöht (Stuhl/Box), die Hüfte beugen und den Oberkörper Richtung Beine bringen. Intensive Hamstring-Dehnung.' },
        { id: 'b-9090-hip',           name: '90/90 Hip Rotations',    prescription: '8–10 pro Seite',  howto: 'Im Sitzen beide Beine 90° angewinkelt (eins vorne, eins seitlich), kontrolliert von einer Seite zur anderen rotieren.' },
        { id: 'b-adductor-rockbacks', name: 'Adductor Rockbacks',     prescription: '10–15',           howto: 'Im Vierfüßlerstand ein Bein gestreckt zur Seite, Fuß am Boden. Die Hüfte nach hinten Richtung Ferse schieben und zurück.' },
      ],
    },
    {
      id: 'c-compression',
      letter: 'C',
      name: 'Compression',
      duration: '10 min',
      goal: 'Aktive Flexibilität – Beine hochziehen können',
      exercises: [
        { id: 'c-seated-leg-lifts',   name: 'Seated Leg Lifts',       prescription: '3×10',            howto: 'Im Langsitz, Beine gestreckt, Hände neben der Hüfte. Beide Beine aktiv vom Boden abheben und langsam wieder senken.' },
        { id: 'c-pike-hold',          name: 'Pike Hold',              prescription: '3×20 Sek',        howto: 'Im Langsitz den Oberkörper über die gestreckten Beine ziehen und aktiv halten – Brust an die Oberschenkel.' },
        { id: 'c-lying-straddle-raises', name: 'Lying Straddle Leg Raises', prescription: '2×15',      howto: 'Auf dem Rücken, Beine in der V-Grätsche. Die gestreckten Beine anheben und kontrolliert senken, ohne im unteren Rücken durchzuhängen.' },
        { id: 'c-standing-pike',      name: 'Standing Pike Compression', prescription: '2×10',         howto: 'Im Stand vorbeugen, Hände hinter die Waden, den Oberkörper aktiv an die Beine ziehen und die Spannung halten.' },
        { id: 'c-straddle-leg-lifts', name: 'Straddle Leg Lifts',     prescription: '2×10/Bein',       howto: 'Im Grätschsitz ein gestrecktes Bein aktiv anheben und senken, dann das andere. Oberkörper aufrecht.' },
        { id: 'c-hanging-leg-raises', name: 'Hanging Leg Raises',     prescription: '2×8–10',          howto: 'An der Stange hängend die gestreckten Beine kontrolliert bis zur Waagerechten (oder höher) anheben, kein Schwung.' },
        { id: 'c-l-sit',              name: 'L-Sit',                  prescription: 'so lange wie möglich', howto: 'Auf Parallettes oder dem Boden gestützt, Beine gestreckt waagerecht nach vorne. Schultern runterdrücken; die Knie anziehen, wenn es zu schwer ist.' },
        { id: 'c-compression-pulses', name: 'Compression Pulses (im Sitzen)', prescription: '20',      howto: 'Im Pike-Sitz kleine, schnelle Hebungen der Beine vom Boden – eine pumpende, aktive Kompression.' },
        { id: 'c-single-leg-compression', name: 'Single Leg Compression Lifts', prescription: '10/Bein', howto: 'Sitzend ein gestrecktes Bein mit den Händen weiter hochziehen, loslassen und aktiv in der Position halten.' },
        { id: 'c-parallettes-switches', name: 'Parallettes L-Sit → Tuck Switches', prescription: '10–15', howto: 'Auf Parallettes gestützt zwischen L-Sit (Beine gestreckt) und Tuck (Knie angezogen) wechseln.' },
        { id: 'c-toe-slides',         name: 'Toe Slides',             prescription: '10–15',           howto: 'Mit Socken auf glattem Boden sitzend die Füße aktiv zum Körper heranziehen (Kompression) und wieder wegschieben.' },
        { id: 'c-band-compressions',  name: 'Band-Assisted Compressions', prescription: '12–15',       howto: 'Ein Band um die Füße, im Sitzen die Beine mit Bandunterstützung aktiv Richtung Brust ziehen.' },
        { id: 'c-knee-to-pike',       name: 'Knee to Pike Compression', prescription: '2×10',          howto: 'Aus angezogenen Knien die Beine zur Pike-Position strecken und die Kompression dabei halten.' },
        { id: 'c-open-v-single',      name: 'Open V single leg on&off', prescription: '2×10',          howto: 'In der offenen V-Position (Grätsche) ein Bein abwechselnd anheben und absenken, die Spannung halten.' },
        { id: 'c-open-v-hold',        name: 'Open V Hold',            prescription: '2×15–20 Sek',     howto: 'Sitzend beide gestreckten Beine in der Grätsche angehoben halten, die Hände stützen leicht – aktive V-Position.' },
        { id: 'c-wall-pike',          name: 'Downwards Wall Pike Compression', prescription: '2×10',    howto: 'Füße an der Wand in der Pike-Position, die Hüfte aktiv beugen und den Oberkörper Richtung Beine/Wand ziehen.' },
        { id: 'c-pike-roll',          name: 'Pike Roll In & Out',     prescription: '10–12',           howto: 'Aus dem Pike kontrolliert in den Rücken rollen und wieder zurück in die Kompression aufrollen.' },
        { id: 'c-tuck-roll',          name: 'Tuck In & Out (mit Black Roll)', prescription: '10–12',   howto: 'Auf der Black Roll balancierend die Knie anziehen (Tuck) und die Beine wieder ausstrecken, ohne das Gleichgewicht zu verlieren.' },
      ],
    },
    {
      id: 'd-kraft',
      letter: 'D',
      name: 'Kraft',
      duration: '8–10 min',
      goal: 'Schultern stark genug für Press',
      exercises: [
        { id: 'd-box-pike-pushups',   name: 'Box Pike Push-Ups',      prescription: '4×5',             howto: 'Füße erhöht auf einer Box, Hüfte hoch im Pike. Den Kopf Richtung Boden absenken und überkopf wieder hochdrücken.' },
        { id: 'd-pike-walkins',       name: 'Pike Walk-Ins',          prescription: '2×10',            howto: 'Aus dem herabschauenden Hund mit den Füßen kleine Schritte Richtung Hände gehen, die Hüfte hebt sich – und wieder zurück.' },
        { id: 'd-elevated-pike-walkins', name: 'Elevated Pike Walk-Ins', prescription: '2×10',         howto: 'Wie Pike Walk-Ins, aber mit erhöhten Füßen für mehr Last auf den Schultern und eine steilere Hüftposition.' },
        { id: 'd-tuck-handstand-hold', name: 'Tuck Handstand Hold',   prescription: '2×20 Sek',        howto: 'Im Handstand (an der Wand oder frei) die Knie zur Brust ziehen und die kompakte Position halten.' },
        { id: 'd-pike-pushups',       name: 'Pike Push-Ups',          prescription: '3×6–8',           howto: 'Vom herabschauenden Hund den Kopf zum Boden absenken und überkopf hochdrücken. Die Ellbogen nicht zu weit ausstellen.' },
        { id: 'd-wall-handstand-hold', name: 'Wall Handstand Hold',   prescription: '2×20–30 Sek',     howto: 'Handstand mit Rücken oder Bauch zur Wand, Körper lang, Schultern aktiv hochschieben.' },
        { id: 'd-handstand-shrugs',   name: 'Handstand Shoulder Shrugs', prescription: '2×8–10',       howto: 'Im Wand-Handstand nur über die Schultern den Körper minimal hoch- und runterschieben (Schulterblätter arbeiten).' },
        { id: 'd-elevated-pike-pushup', name: 'Elevated Pike Push-Up', prescription: '3×5–8',          howto: 'Pike Push-Up mit erhöhten Füßen – fast senkrechte Schulterbelastung, näher am Handstand-Push.' },
        { id: 'd-wall-lean-hold',     name: 'Wall Lean Hold (Nase zur Wand)', prescription: '20–30 Sek', howto: 'Bauch und Nase nah zur Wand im Handstand, Körper kerzengerade, Schultern voll geöffnet und hochgeschoben.' },
        { id: 'd-planche-lean',       name: 'Planche Lean (leicht)',  prescription: '15–25 Sek',       howto: 'Im Plank die Schultern weit vor die Hände schieben, das Gewicht nach vorne – baut Stützkraft für den Press auf.' },
        { id: 'd-dolphin-pushups',    name: 'Dolphin Push-Ups',       prescription: '8–12',            howto: 'Auf den Unterarmen im Pike, die Schultern über die Hände nach vorne und zurück wiegen – wie ein Delphin.' },
        { id: 'd-handstand-toe-pulls', name: 'Handstand Toe Pulls',   prescription: '5–10',            howto: 'Im Wand-Handstand vorsichtig die Zehen von der Wand lösen und kurz frei balancieren, dann zurück.' },
        { id: 'd-band-shoulder-flexion', name: 'Band Shoulder Flexion Raises', prescription: '12–15',  howto: 'Band unter den Füßen, die gestreckten Arme nach vorne/oben über den Kopf führen – kräftigt die Schulterbeugung.' },
      ],
    },
    {
      id: 'e-skill',
      letter: 'E',
      name: 'Skill',
      duration: '10–15 min',
      goal: 'Den eigentlichen Press lernen',
      exercises: [
        { id: 'e-negative-press',     name: 'Negative Press to Handstand', prescription: '3–5×',       howto: 'Aus dem Handstand mit gestreckten Armen langsam und kontrolliert in den Pike/Stand absenken – so lange wie möglich bremsen.' },
        { id: 'e-press-attempts',     name: 'Press-Versuche',         prescription: '5–10×',           howto: 'Aus dem Pike-Stand oder der Grätsche mit gestreckten Armen versuchen, kontrolliert in den Handstand zu drücken. Füße erhöht ist erlaubt.' },
        { id: 'e-tuck-press',         name: 'Tuck Press (gebeugte Knie)', prescription: '5–8×',        howto: 'Mit angezogenen Knien aus dem Stütz in den Handstand drücken – die leichtere Press-Variante über den Tuck.' },
        { id: 'e-box-press',          name: 'Box Press (Füße auf Kiste)', prescription: '5–8 Versuche', howto: 'Füße auf einer Box, die Hüfte über die Schultern bringen und die gestreckten Beine in den Handstand pressen.' },
        { id: 'e-band-press',         name: 'Band-Assisted Press',    prescription: '5–8',             howto: 'Das Band gibt Unterstützung nach oben, damit du das Press-Gefühl mit weniger Last trainieren kannst.' },
        { id: 'e-straddle-negatives', name: 'Straddle Press Negatives', prescription: '3–5',           howto: 'Aus dem Handstand in der Grätsche ganz langsam herablassen – exzentrisch die Press-Kraft aufbauen.' },
        { id: 'e-toe-tap-two',        name: 'Toe Tap Press Drill (beidbeinig)', prescription: '8–10',  howto: 'Mit leichtem beidbeinigem Abdruck kurz in die Press-Position antippen und das Hochkommen spüren.' },
        { id: 'e-toe-tap-one',        name: 'Toe Tap Press Drill (einbeinig)', prescription: '10 pro Seite', howto: 'Einbeiniger leichter Abdruck in Richtung Handstand-Press, kontrolliert pro Seite.' },
        { id: 'e-compression-lean',   name: 'Compression → Lean Drill', prescription: '10 Wdh.',       howto: 'Die wichtige Kopplung: aus der Kompression in den Schulter-Lean übergehen – genau diese Bewegung trägt dich in den Press.' },
        { id: 'e-headstand-blocks',   name: 'Kopfstand (auf Yoga-Blöcken)', prescription: '5×',        howto: 'Kopfstand auf zwei Yoga-Blöcken, um die Press- und Balancebewegung sicher und mit weniger Druck auf den Kopf zu üben.' },
        { id: 'e-wall-pike-leg-lift', name: 'Wall Pike Leg Lift',     prescription: '8–10',            howto: 'In der Wand-Pike-Position (Füße an der Wand) ein gestrecktes Bein aktiv anheben – Kompression unter Last.' },
      ],
    },
  ],
};
